import type { IndicatorDef } from './types'

export const INDICATORS: readonly IndicatorDef[] = [
  // 변동성
  {
    id: 'VIXCLS',
    name: 'VIX',
    nameKr: 'VIX 지수',
    category: 'volatility',
    source: 'fred',
    sourceId: 'VIXCLS',
    fallbackSource: 'yfinance',
    fallbackSourceId: '^VIX',
    unit: 'index',
    precision: 2,
    thresholds: { normal: [0, 20], watch: [20, 30], alert: [30, 999], direction: 'above' },
    updateCadence: 'daily',
    description: 'S&P 500 옵션 30일 implied volatility, 공포지수',
    mainView: true,
  },
  {
    id: 'MOVE',
    name: 'MOVE Index',
    nameKr: 'MOVE 지수',
    category: 'volatility',
    source: 'yfinance',
    sourceId: '^MOVE',
    fallbackSource: 'manual',
    fallbackSourceId: 'MOVE',
    unit: 'index',
    precision: 1,
    thresholds: { normal: [0, 100], watch: [100, 150], alert: [150, 999], direction: 'above' },
    updateCadence: 'daily',
    description: '미국채 옵션 변동성 지수 (채권 VIX). yfinance 차단 시 manual entry.',
  },

  // 인플레이션
  {
    id: 'CPIAUCSL',
    name: 'CPI',
    nameKr: '미국 CPI',
    category: 'inflation',
    source: 'fred',
    sourceId: 'CPIAUCSL',
    unit: 'index',
    precision: 2,
    thresholds: { normal: [0, 3], watch: [3, 4], alert: [4, 999], direction: 'above' },
    updateCadence: 'monthly',
    transform: 'yoy',
    releaseTimeET: '08:30',
    description: '미국 소비자물가지수 YoY %',
  },
  {
    id: 'CPILFESL',
    name: 'Core CPI',
    nameKr: '미국 근원 CPI',
    category: 'inflation',
    source: 'fred',
    sourceId: 'CPILFESL',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 2.5], watch: [2.5, 4], alert: [4, 999], direction: 'above' },
    updateCadence: 'monthly',
    transform: 'yoy',
    releaseTimeET: '08:30',
    description: 'Core CPI YoY % (식품·에너지 제외), Fed 정책 타깃',
    mainView: true,
  },
  {
    id: 'PPIACO',
    name: 'PPI',
    nameKr: 'PPI',
    category: 'inflation',
    source: 'fred',
    sourceId: 'PPIACO',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 2], watch: [2, 4], alert: [4, 999], direction: 'above' },
    updateCadence: 'monthly',
    transform: 'yoy',
    releaseTimeET: '08:30',
    description: '생산자물가지수 YoY %, CPI 1-3M 선행',
  },
  {
    id: 'T10YIE',
    name: 'BEI 10Y',
    nameKr: '10Y 기대인플레',
    category: 'inflation',
    source: 'fred',
    sourceId: 'T10YIE',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 2.5], watch: [2.5, 3], alert: [3, 999], direction: 'above' },
    updateCadence: 'daily',
    description: '10Y 명목금리 - TIPS = 기대인플레이션',
  },

  // 금리
  {
    id: 'DFF',
    name: 'Fed Funds',
    nameKr: 'Fed Funds Rate',
    category: 'rates',
    source: 'fred',
    sourceId: 'DFF',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 5.5], watch: [5.5, 6.5], alert: [6.5, 999], direction: 'above' },
    updateCadence: 'daily',
    description: '미국 정책금리',
  },
  {
    id: 'DGS3MO',
    name: 'US 3M',
    nameKr: '미국채 3M',
    category: 'rates',
    source: 'fred',
    sourceId: 'DGS3MO',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 100], watch: [0, 100], alert: [0, 100], direction: 'above' },
    updateCadence: 'daily',
    hidden: true,
  },
  {
    id: 'DGS2',
    name: 'US 2Y',
    nameKr: '미국채 2Y',
    category: 'rates',
    source: 'fred',
    sourceId: 'DGS2',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 100], watch: [0, 100], alert: [0, 100], direction: 'above' },
    updateCadence: 'daily',
    hidden: true,
  },
  {
    id: 'DGS3',
    name: 'US 3Y',
    nameKr: '미국채 3Y',
    category: 'rates',
    source: 'fred',
    sourceId: 'DGS3',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 100], watch: [0, 100], alert: [0, 100], direction: 'above' },
    updateCadence: 'daily',
  },
  {
    id: 'DGS10',
    name: 'US 10Y',
    nameKr: '미국채 10Y',
    category: 'rates',
    source: 'fred',
    sourceId: 'DGS10',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 4.5], watch: [4.5, 5], alert: [5, 999], direction: 'above' },
    updateCadence: 'daily',
    description: '글로벌 할인율의 기준',
    mainView: true,
  },
  {
    id: 'DGS30',
    name: 'US 30Y',
    nameKr: '미국채 30Y',
    category: 'rates',
    source: 'fred',
    sourceId: 'DGS30',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 5], watch: [5, 5.5], alert: [5.5, 999], direction: 'above' },
    updateCadence: 'daily',
  },
  {
    id: 'T10Y2Y',
    name: 'T10Y2Y',
    nameKr: '10Y-2Y 스프레드',
    category: 'rates',
    source: 'fred',
    sourceId: 'T10Y2Y',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0.5, 999], watch: [0, 0.5], alert: [-999, 0], direction: 'below' },
    updateCadence: 'daily',
    description: '학술적 침체 예측력 1위',
    inverted: true,
  },
  {
    id: 'T10Y3M',
    name: 'T10Y3M',
    nameKr: '10Y-3M 스프레드',
    category: 'rates',
    source: 'fred',
    sourceId: 'T10Y3M',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [1, 999], watch: [0, 1], alert: [-999, 0], direction: 'below' },
    updateCadence: 'daily',
    description: 'NY Fed 침체확률 모델 핵심 입력',
    inverted: true,
    hidden: true,
  },

  // 신용
  {
    id: 'BAMLH0A0HYM2',
    name: 'HY OAS',
    nameKr: 'HY 스프레드',
    category: 'credit',
    source: 'fred',
    sourceId: 'BAMLH0A0HYM2',
    unit: 'pct',
    precision: 2,
    thresholds: { normal: [0, 5], watch: [5, 7], alert: [7, 999], direction: 'above' },
    updateCadence: 'daily',
    description: '하이일드 스프레드, 주식 1-3M 선행',
    mainView: true,
  },

  // 글로벌·통화
  {
    id: 'DTWEXBGS',
    name: 'DXY',
    nameKr: '달러 인덱스',
    category: 'fx',
    source: 'yfinance',
    sourceId: 'DX-Y.NYB',
    fallbackSource: 'fred',
    fallbackSourceId: 'DTWEXBGS',
    unit: 'index',
    precision: 2,
    thresholds: { normal: [0, 100], watch: [100, 105], alert: [105, 999], direction: 'above' },
    updateCadence: 'daily',
    description: 'ICE 달러 인덱스 (시장 표준). FRED 광의 무역가중은 폴백.',
  },
  {
    id: 'DCOILWTICO',
    name: 'WTI',
    nameKr: 'WTI 원유',
    category: 'commodity',
    source: 'yfinance',
    sourceId: 'CL=F',
    fallbackSource: 'fred',
    fallbackSourceId: 'DCOILWTICO',
    unit: 'usd',
    precision: 2,
    thresholds: { normal: [50, 90], watch: [90, 110], alert: [110, 999], direction: 'above' },
    updateCadence: 'daily',
  },
  {
    id: 'GOLD',
    name: 'Gold',
    nameKr: '금',
    category: 'commodity',
    source: 'yfinance',
    sourceId: 'GC=F',
    fallbackSource: 'stooq',
    fallbackSourceId: 'gc.f',
    unit: 'usd',
    precision: 2,
    thresholds: { normal: [0, 9999], watch: [0, 9999], alert: [0, 9999], direction: 'above' },
    updateCadence: 'daily',
    description: 'COMEX gold futures (FRED LBMA series discontinued 2017)',
  },

  // 한국 매크로
  {
    id: 'KR_EXPORT',
    name: 'KR Export YoY',
    nameKr: '한국 수출 YoY',
    category: 'korea',
    source: 'kosis',
    sourceId: 'EXPORT_TOTAL_YOY',
    fallbackSource: 'manual',
    fallbackSourceId: 'KR_EXPORT',
    unit: 'pct',
    precision: 1,
    thresholds: { normal: [0, 999], watch: [-5, 0], alert: [-999, -5], direction: 'below' },
    updateCadence: 'monthly',
    releaseTimeET: '20:00',
    description: '한국 수출 전년동월대비, KOSPI EPS와 r≈0.7. 산자부 발표 후 manual entry 권장.',
    inverted: true,
  },
  {
    id: 'KR_EXPORT_SEMI',
    name: 'KR Semi YoY',
    nameKr: '반도체 수출 YoY',
    category: 'korea',
    source: 'kosis',
    sourceId: 'EXPORT_SEMICONDUCTOR_YOY',
    fallbackSource: 'manual',
    fallbackSourceId: 'KR_EXPORT_SEMI',
    unit: 'pct',
    precision: 1,
    thresholds: { normal: [0, 999], watch: [-10, 0], alert: [-999, -10], direction: 'below' },
    updateCadence: 'monthly',
    description: '반도체 수출 YoY (HS 8542). manual entry 권장.',
    inverted: true,
  },
  {
    id: 'KR_TB',
    name: 'KR Trade Balance',
    nameKr: '한국 무역수지',
    category: 'korea',
    source: 'kosis',
    sourceId: 'TRADE_BALANCE',
    fallbackSource: 'manual',
    fallbackSourceId: 'KR_TB',
    unit: 'kbusd',
    precision: 1,
    thresholds: { normal: [0, 999], watch: [-50, 0], alert: [-999, -50], direction: 'below' },
    updateCadence: 'monthly',
    description: '한국 무역수지 (수출-수입). manual entry 권장.',
    inverted: true,
  },
  {
    id: 'USDKRW',
    name: 'USD/KRW',
    nameKr: '원/달러',
    category: 'fx',
    source: 'ecos',
    sourceId: '731Y001/0000001',
    fallbackSource: 'yfinance',
    fallbackSourceId: 'KRW=X',
    unit: 'krw',
    precision: 2,
    thresholds: { normal: [1100, 1300], watch: [1300, 1400], alert: [1400, 9999], direction: 'above' },
    updateCadence: 'daily',
    description: '한국 투자자 환 익스포저 (ECOS 731Y001 / ITEM 0000001 미국달러)',
  },
  {
    id: 'KOSPI',
    name: 'KOSPI',
    nameKr: 'KOSPI 지수',
    category: 'korea',
    source: 'yfinance',
    sourceId: '^KS11',
    fallbackSource: 'stooq',
    fallbackSourceId: '^kospi',
    unit: 'index',
    precision: 2,
    thresholds: { normal: [0, 99999], watch: [0, 99999], alert: [0, 99999], direction: 'above' },
    updateCadence: 'daily',
  },
  {
    id: 'SP500',
    name: 'S&P 500',
    nameKr: 'S&P 500',
    category: 'commodity',
    source: 'yfinance',
    sourceId: '^GSPC',
    fallbackSource: 'fred',
    fallbackSourceId: 'SP500',
    unit: 'index',
    precision: 2,
    thresholds: { normal: [0, 99999], watch: [0, 99999], alert: [0, 99999], direction: 'above' },
    updateCadence: 'daily',
  },
] as const

export function getIndicator(id: string): IndicatorDef | undefined {
  return INDICATORS.find((i) => i.id === id)
}

export const MAIN_VIEW_INDICATORS = INDICATORS.filter((i) => i.mainView).map((i) => i.id)
export const ALL_INDICATOR_IDS = INDICATORS.map((i) => i.id)
