import type { SignalRule } from './types'

export const RULES: readonly SignalRule[] = [
  // ── Volatility ──
  {
    id: 'VIX_WARN',
    name: '변동성 경계 (VIX > 30)',
    severity: 'warning',
    category: 'volatility',
    type: 'risk',
    indicators: ['VIXCLS'],
    condition: 'VIXCLS.latest > 30',
    cooldownHours: 168,
    rationale: '1990 이후 거래일 15% 구간. 풋 헤지 비용 2배 수준',
    falsePositiveNote: '2018 Volmaggedon — 5일 만에 정상화. 단발성 스파이크 주의',
    actionHint: '성장주 일부 차익실현 검토, 현금 5~10%p 확대',
  },
  {
    id: 'VIX_PANIC',
    name: '패닉 국면 (VIX > 40)',
    severity: 'critical',
    category: 'volatility',
    type: 'risk',
    indicators: ['VIXCLS'],
    condition: 'VIXCLS.latest > 40',
    cooldownHours: 168,
    rationale: '1990 이후 3% 미만 관측, 12M 후 평균 +15% 이상',
    historicalTriggers: '2008.09, 2020.03, 2022 단발 — 모두 12M 후 시장 회복',
    falsePositiveNote: '2008.09 첫 돌파 후 SPX 추가 -30% 하락. 단일 시그널만으로 진입 금지',
    actionHint: '현금 1/3 분할 매수, 6개월 시계 분산',
  },

  // ── Rates / Recession ──
  {
    id: 'T10Y2Y_INVERT',
    name: '10Y-2Y 역전 (60일 평균)',
    severity: 'warning',
    category: 'recession',
    type: 'risk',
    indicators: ['T10Y2Y'],
    condition: 'T10Y2Y.rollingMean60 < 0',
    cooldownHours: 720,
    rationale: 'Estrella-Mishkin: 평균 12~18M 선행 침체',
    falsePositiveNote: '2022~ 역전 후 2026년 현재 NBER 침체 미선언 (시차 변동성)',
    actionHint: '장기채 비중 점검, 시클리컬 축소 검토',
  },
  {
    id: 'T10Y3M_INVERT',
    name: '10Y-3M 역전',
    severity: 'warning',
    category: 'recession',
    type: 'risk',
    indicators: ['T10Y3M'],
    condition: 'T10Y3M.latest < 0',
    cooldownHours: 720,
    rationale: 'NY Fed 침체확률 모델 핵심 입력',
    falsePositiveNote: '2019 트리거 후 코로나 외생충격으로 인과 모호',
    actionHint: 'T10Y2Y와 중첩 시 복합 룰 (RECESSION_COMPOSITE) 점검',
  },

  // ── Inflation ──
  {
    id: 'CORE_CPI_HOT',
    name: '근원 인플레 과열 (Core CPI > 4%)',
    severity: 'warning',
    category: 'inflation',
    type: 'risk',
    indicators: ['CPILFESL'],
    condition: 'CPILFESL.yoy > 4',
    cooldownHours: 720,
    rationale: 'Fed 실질 타깃 4% 돌파 시 12M SPX 평균 +3% (vs 평균 +10%)',
    falsePositiveNote: '1991 걸프전 단발 돌파 후 6M 내 정상화',
    actionHint: '장기채 축소, 듀레이션 단축. 금융/에너지 회전 검토',
  },

  // ── Credit ──
  {
    id: 'HY_OAS_STRESS',
    name: '신용 스트레스 (HY OAS > 600bp)',
    severity: 'warning',
    category: 'recession',
    type: 'risk',
    indicators: ['BAMLH0A0HYM2'],
    condition: 'BAMLH0A0HYM2.latest > 6',
    cooldownHours: 168,
    rationale: '신용시장이 주식보다 1~3M 선행 (Gilchrist & Zakrajšek 2012)',
    falsePositiveNote: '2015~16 에너지 단독 확대 (8M 만에 정상화)',
    actionHint: 'HY ETF 비중 축소, IG 다운트레이드 검토',
  },
  {
    id: 'HY_OAS_PANIC',
    name: '신용 패닉 (HY OAS > 800bp, 역발상 기회)',
    severity: 'critical',
    category: 'opportunity',
    type: 'opportunity',
    indicators: ['BAMLH0A0HYM2'],
    condition: 'BAMLH0A0HYM2.latest > 8',
    cooldownHours: 720,
    rationale: '1997 이후 5회 미만 관측, 12M 후 HY +20% / SPX +15%',
    falsePositiveNote: '2008.09 800 돌파 후 1700까지 추가 확대. 진입 분할 필수',
    actionHint: 'HY ETF 분할 진입, 미국 시클리컬/반도체 매수 후보',
  },

  // ── FX ──
  {
    id: 'DXY_STRONG',
    name: '달러 강세 (DXY > 105)',
    severity: 'info',
    category: 'volatility',
    type: 'risk',
    indicators: ['DTWEXBGS'],
    condition: 'DTWEXBGS.latest > 105',
    cooldownHours: 336,
    rationale: '신흥국 자본유출, KOSPI 외국인 매도 동행',
    falsePositiveNote: '2022.11~2023.01 강세 유지 + 위험자산 회복 동시',
    actionHint: '미국 자산으로 일부 분산, 한국 수출주 단기 부담 인지',
  },

  // ── Korea ──
  {
    id: 'KR_EXPORT_WEAK',
    name: '한국 수출 둔화 (YoY < -5%)',
    severity: 'warning',
    category: 'korea',
    type: 'risk',
    indicators: ['KR_EXPORT'],
    condition: 'KR_EXPORT.latest < -5',
    cooldownHours: 720,
    rationale: 'KOSPI Fwd EPS와 r≈0.7, EPS 6~9M 후 하향',
    falsePositiveNote: '2023 -10%대에도 AI/반도체 모멘텀으로 KOSPI 상승',
    actionHint: 'KOSPI 시클리컬 점검, 반도체 별도 추적',
  },
  {
    id: 'KR_EXPORT_CRASH',
    name: '한국 수출 급락 (YoY < -10%, 3M 연속)',
    severity: 'critical',
    category: 'korea',
    type: 'risk',
    indicators: ['KR_EXPORT'],
    condition: 'KR_EXPORT.sustainedBelow(-10, 3)',
    cooldownHours: 720,
    rationale: '1990 이후 5회만 관측, 모두 KOSPI -15% 이상',
    falsePositiveNote: '2023 급락은 시장 충격 짧음 (오히려 매수 기회)',
    actionHint: 'KOSPI 5~10%p 축소 + 6M 분할 재진입 계획',
  },
  {
    id: 'USDKRW_HIGH',
    name: '원/달러 환율 부담 (USD/KRW > 1350)',
    severity: 'info',
    category: 'korea',
    type: 'risk',
    indicators: ['USDKRW'],
    condition: 'USDKRW.latest > 1350',
    cooldownHours: 336,
    rationale: '2008·2022·2024 외국인 누적 순매도 임계',
    falsePositiveNote: '2024 1350+ 장기 체류에도 KOSPI 박스권 유지',
    actionHint: '미국 자산 신규 진입 환 부담 인지, 한국 수출 대형주 환 효과',
  },

  // ── Composite ──
  {
    id: 'RECESSION_COMPOSITE',
    name: '침체 임박 복합 시그널',
    severity: 'critical',
    category: 'recession',
    type: 'risk',
    indicators: ['T10Y2Y', 'BAMLH0A0HYM2', 'VIXCLS'],
    condition: 'T10Y2Y.sustainedBelow(0, 6mo) AND BAMLH0A0HYM2.latest > 6 AND VIXCLS.rollingMean60 > 25',
    cooldownHours: 720,
    rationale: '신용·금리·변동성 3개 시장 동시 침체 가격화',
    historicalTriggers: '1990, 2000~01, 2007~08, 2019.08~2020.02 — 모두 12M 내 NBER 침체 또는 SPX -20%',
    falsePositiveNote: '2022~23 사이클은 미충족 → 침체 미발생과 일치 (robustness)',
    actionHint: '주식 비중 10~20%p 축소. 장기채(TLT) 비중 확대. 6M 분할 실행',
  },
  {
    id: 'INFLATION_REACCEL',
    name: '인플레이션 재가속',
    severity: 'critical',
    category: 'inflation',
    type: 'risk',
    indicators: ['CPILFESL', 'PPIACO', 'DCOILWTICO'],
    condition: 'CPILFESL.momAnn3MStreak > 3.6 AND PPIACO.yoy > 3 AND DCOILWTICO.yoy > 20',
    cooldownHours: 720,
    rationale: 'Fed 인하 지연 시나리오를 시장이 가격화',
    historicalTriggers: '1973~74, 1979~80, 2008 상반기, 2022.01~06',
    falsePositiveNote: '2011 상반기 유가 급등기는 Core CPI 미달로 본 룰 미발화',
    actionHint: '장기채 축소, 듀레이션 단축. 에너지/금융/금 비중 점검',
  },
  {
    id: 'BUY_PANIC',
    name: '패닉 역발상 매수 후보',
    severity: 'critical',
    category: 'opportunity',
    type: 'opportunity',
    indicators: ['VIXCLS', 'BAMLH0A0HYM2', 'SP500'],
    condition: 'VIXCLS.latest > 35 AND BAMLH0A0HYM2.latest > 8 AND SP500.pctBelow200dma < -15',
    cooldownHours: 720,
    rationale: '공포·신용·가격 3차원 극단 동시 도달',
    historicalTriggers: '1998 LTCM, 2001~02 닷컴, 2008.10~2009.03 GFC, 2020.03 코로나 — 모두 12M 후 SPX +20% 이상',
    falsePositiveNote: '2008.10 1차 트리거 후 SPX 추가 -30% 하락 — 바닥 신호 아님',
    actionHint: '분할 매수 시작, 6개월 시계로 분산. Fed 반응 별도 모니터',
  },
  {
    id: 'KR_SLOWDOWN_COMPOSITE',
    name: '한국 경기 둔화 복합',
    severity: 'critical',
    category: 'korea',
    type: 'risk',
    indicators: ['KR_EXPORT', 'KR_EXPORT_SEMI', 'DTWEXBGS'],
    condition: 'KR_EXPORT.sustainedBelow(-5, 3) AND KR_EXPORT_SEMI.latest < -10 AND DTWEXBGS.latest > 105',
    cooldownHours: 720,
    rationale: '한국 수출 + 반도체 + 달러 강세 동시 → KOSPI 이익 하향',
    falsePositiveNote: '외국인 수급 데이터 추가 시 robustness 개선',
    actionHint: 'KOSPI 비중 축소, 미국 방어주/장기채 헤지 검토',
  },
  {
    id: 'EARLY_RECOVERY',
    name: '회복 초기',
    severity: 'warning',
    category: 'opportunity',
    type: 'opportunity',
    indicators: ['T10Y2Y', 'KR_EXPORT', 'VIXCLS'],
    condition: 'T10Y2Y.signFlipPositive AND KR_EXPORT.signFlipPositive AND VIXCLS.latest < 20',
    cooldownHours: 720,
    rationale: '장단기 금리역전 해소 + 한국 수출 플러스 전환 + 변동성 안정',
    historicalTriggers: '2003 초반, 2009.06~, 2020.06~',
    actionHint: '한국 시클리컬/반도체, 미국 성장주, 이머징 ETF 비중 확대',
  },
  {
    id: 'STAGFLATION_COMPOSITE',
    name: '스태그플레이션 복합',
    severity: 'critical',
    category: 'inflation',
    type: 'risk',
    indicators: ['CPILFESL', 'DTWEXBGS', 'KR_EXPORT'],
    condition: 'CPILFESL.yoy > 4 AND DTWEXBGS.latest > 105 AND KR_EXPORT.latest < 0',
    cooldownHours: 720,
    rationale: '인플레 + 달러 강세 + 글로벌 수요 둔화 동시',
    falsePositiveNote: 'GDP nowcast 미통합 — 향후 한국·미국 PMI 추가 권장',
    actionHint: '원자재·금·필수소비재 비중 확대, 성장주 축소',
  },
] as const

export function getRule(id: string): SignalRule | undefined {
  return RULES.find((r) => r.id === id)
}
